/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Dao.DaoLicencia;
import Dao.DaoTitular;
import Dao.DataAccessLayerException;
import Entidades.Licencia;
import Entidades.Titular;
import Entidades.TitularAuxParaTabla;
import Gestores.GestorAdministrativo;
import java.util.Date;
import javax.swing.JOptionPane;
import Gestores.GestorLicencias;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

/**
 *
 * @author mueve el toto
 */
public class EmitirLicencia extends javax.swing.JFrame {
    TitularAuxParaTabla titular_aux;
    Titular nuevoTitular;
    private Boolean desdeNuevoTitular = false;
    
    /**
     * Creates new form Inicio2
     */
    
    public EmitirLicencia() {
        //borrar todo cuando este listo el metodo de abajo
        initComponents();
        setTitle("Emitir Licencia");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        //borrar hasta aca
    }
    
    public EmitirLicencia(TitularAuxParaTabla titularAuxParaTabla) {
        titular_aux = titularAuxParaTabla; 
        initComponents();
        setTitle("Emitir Licencia");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        
        //se setean los datos no modificables (datos del titular)
        txt_nombre.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getNombre())));
        txt_apellido.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getApellido())));
        txt_nro_doc.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getDni())));
        txt_direccion.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getDomicilio())));
        txt_fecha_nac.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getFechaNac())));
        txt_tipo_doc.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getTipoDni())));
        txt_grupo_sanguineo.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getGrupoSanguineo())));
        txt_factor_sanguineo.setText((String.valueOf(titularAuxParaTabla.getTitularOriginal().getFactorSanguineo())));
        
        this.nuevoTitular = titularAuxParaTabla.getTitularOriginal();
    }
    
    public EmitirLicencia(Titular nuevoTitular){
        this.nuevoTitular = nuevoTitular; 
        this.nuevoTitular.setFechaUltimaActualizacion(new Date());
        initComponents();
        setTitle("Emitir Licencia");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
   
        //se setean los datos no modificables (datos del titular)
        txt_nombre.setText(nuevoTitular.getNombre());
        txt_apellido.setText(nuevoTitular.getApellido());
        txt_nro_doc.setText(nuevoTitular.getDni());
        txt_direccion.setText(nuevoTitular.getDomicilio());
        Date date = nuevoTitular.getFechaNac();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = format.format(date);
        txt_fecha_nac.setText(dateString);
        txt_tipo_doc.setText(nuevoTitular.getTipoDni());
        txt_grupo_sanguineo.setText(nuevoTitular.getGrupoSanguineo());
        txt_factor_sanguineo.setText(nuevoTitular.getFactorSanguineo());
        desdeNuevoTitular = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_superior = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_centro = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_tipo_doc = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_nro_doc = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha_nac = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        listaClase = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        jPanel12 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_grupo_sanguineo = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_factor_sanguineo = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        listaDonante = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        jPanel8 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jPanel_inferior = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        boton_atras = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        boton_emitir_licencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setRequestFocusEnabled(false);
        jPanel_superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel3.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(250, 60));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Usuario: ");
        jPanel5.add(jLabel8, new java.awt.GridBagConstraints());

        txt_user.setText("jLabel9");
        jPanel5.add(txt_user, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(250, 60));
        jPanel4.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel15.setText("Nombre:");
        jPanel4.add(jLabel15, new java.awt.GridBagConstraints());

        txt_nombre_user.setText("jLabel9");
        jPanel4.add(txt_nombre_user, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel4);

        jPanel_superior.add(jPanel3);

        jPanel2.setMaximumSize(new java.awt.Dimension(750, 120));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Emitir Licencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel_superior.add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel1);

        getContentPane().add(jPanel_superior);

        jPanel_centro.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setLayout(new javax.swing.BoxLayout(jPanel_centro, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(1280, 400));
        jPanel9.setMinimumSize(new java.awt.Dimension(1280, 400));
        jPanel9.setPreferredSize(new java.awt.Dimension(1280, 400));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel10.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel10.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel16.add(jLabel2);

        txt_nombre.setText("jLabel15");
        txt_nombre.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_nombre.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_nombre.setName("li_nombre"); // NOI18N
        txt_nombre.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel16.add(txt_nombre);
        txt_nombre.getAccessibleContext().setAccessibleName("li_nombre");

        jPanel10.add(jPanel16);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Apellido:");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel9.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel15.add(jLabel9);

        txt_apellido.setText("jLabel15");
        txt_apellido.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_apellido.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_apellido.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel15.add(txt_apellido);

        jPanel10.add(jPanel15);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tipo Doc:");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel14.add(jLabel3);

        txt_tipo_doc.setText("jLabel15");
        txt_tipo_doc.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_tipo_doc.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_tipo_doc.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel14.add(txt_tipo_doc);

        jPanel10.add(jPanel14);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("N° Doc:");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel13.add(jLabel10);

        txt_nro_doc.setText("jLabel15");
        txt_nro_doc.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_nro_doc.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_nro_doc.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel13.add(txt_nro_doc);

        jPanel10.add(jPanel13);

        jPanel9.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel11.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel19.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel19.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Dirección:");
        jLabel11.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel19.add(jLabel11);

        txt_direccion.setText("jLabel15");
        txt_direccion.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_direccion.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_direccion.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel19.add(txt_direccion);

        jPanel11.add(jPanel19);

        jPanel18.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel18.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel18.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha Nac.:");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel18.add(jLabel4);

        txt_fecha_nac.setText("jLabel15");
        txt_fecha_nac.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_fecha_nac.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_fecha_nac.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel18.add(txt_fecha_nac);

        jPanel11.add(jPanel18);

        jPanel17.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel17.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel17.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Clase:");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel17.add(jLabel5);

        listaClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        listaClase.setMaximumSize(new java.awt.Dimension(225, 35));
        listaClase.setMinimumSize(new java.awt.Dimension(225, 35));
        listaClase.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel17.add(listaClase);

        jPanel11.add(jPanel17);
        jPanel11.add(filler1);

        jPanel9.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel12.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel12.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel22.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel22.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel22.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Grupo Sanguineo:");
        jLabel13.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel13.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel22.add(jLabel13);

        txt_grupo_sanguineo.setText("jLabel15");
        txt_grupo_sanguineo.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_grupo_sanguineo.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_grupo_sanguineo.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel22.add(txt_grupo_sanguineo);

        jPanel12.add(jPanel22);

        jPanel21.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel21.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel21.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Factor RH:");
        jLabel14.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel14.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel21.add(jLabel14);

        txt_factor_sanguineo.setText("jLabel15");
        txt_factor_sanguineo.setMaximumSize(new java.awt.Dimension(225, 35));
        txt_factor_sanguineo.setMinimumSize(new java.awt.Dimension(225, 35));
        txt_factor_sanguineo.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel21.add(txt_factor_sanguineo);

        jPanel12.add(jPanel21);

        jPanel20.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel20.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel20.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Donante:");
        jLabel12.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel12.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel20.add(jLabel12);

        listaDonante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        listaDonante.setMaximumSize(new java.awt.Dimension(225, 35));
        listaDonante.setMinimumSize(new java.awt.Dimension(225, 35));
        listaDonante.setPreferredSize(new java.awt.Dimension(225, 35));
        jPanel20.add(listaDonante);

        jPanel12.add(jPanel20);
        jPanel12.add(filler2);

        jPanel9.add(jPanel12);

        jPanel_centro.add(jPanel9);

        jPanel8.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel8.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel8.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel23.setMaximumSize(new java.awt.Dimension(250, 100));
        jPanel23.setMinimumSize(new java.awt.Dimension(250, 100));
        jPanel23.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("Limitaciones/");
        jPanel23.add(jLabel6, new java.awt.GridBagConstraints());

        jLabel7.setText("Observaciones:");
        jPanel23.add(jLabel7, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel23);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(600, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(600, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 100));

        txt_observaciones.setColumns(20);
        txt_observaciones.setLineWrap(true);
        txt_observaciones.setRows(5);
        txt_observaciones.setToolTipText("");
        txt_observaciones.setWrapStyleWord(true);
        txt_observaciones.setName("li_nombre"); // NOI18N
        txt_observaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_observacionesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_observaciones);

        jPanel8.add(jScrollPane2);

        jPanel_centro.add(jPanel8);

        getContentPane().add(jPanel_centro);

        jPanel_inferior.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        boton_atras.setText("Atrás");
        boton_atras.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_atras.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_atras.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 296, 36, 296);
        jPanel7.add(boton_atras, gridBagConstraints);

        jPanel_inferior.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        boton_emitir_licencia.setText("Finalizar");
        boton_emitir_licencia.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_emitir_licencia.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_emitir_licencia.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_emitir_licencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_emitir_licenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 286, 36, 286);
        jPanel6.add(boton_emitir_licencia, gridBagConstraints);

        jPanel_inferior.add(jPanel6);

        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atrasActionPerformed
        
        if(desdeNuevoTitular){
            NuevoTitular pantalla = new NuevoTitular(nuevoTitular);
            pantalla.setVisible(true);
            dispose();
        }
        else{
            GestionLicencias obj = new GestionLicencias();
            obj.setVisible(true);
            dispose(); 
        }
        
    }//GEN-LAST:event_boton_atrasActionPerformed

    private void boton_emitir_licenciaActionPerformed(java.awt.event.ActionEvent evt) {
        
        Licencia nuevaLicencia = new Licencia();
        nuevaLicencia.setAdministrativo(GestorAdministrativo.getInstance().getAdministrativo());
        
        nuevoTitular.setAdministrativo(GestorAdministrativo.getInstance().getAdministrativo());
        DaoTitular daoTitular = new DaoTitular();
        DaoLicencia daoLicencia = new DaoLicencia();

        nuevaLicencia.setTitular(nuevoTitular);
        String ls_clase = (String) listaClase.getSelectedItem();
        nuevaLicencia.setClase(ls_clase);
        String ls_donante = (String) listaDonante.getSelectedItem();
        nuevaLicencia.setDonante(ls_donante);
        nuevaLicencia.setEstado("Original");
        String ls_observaciones = (String) txt_observaciones.getText();
        nuevaLicencia.setObservaciones(ls_observaciones);

        Date fechaRegistro = new Date();

        nuevaLicencia.setFechaRegistro(fechaRegistro);

        Date fechaVencimiento = GestorLicencias.calcularFechaLicencia(nuevoTitular.getFechaNac(), null);

        nuevaLicencia.setFechaVenc(fechaVencimiento);

        nuevoTitular.setLicencias(nuevaLicencia);

        try{
            if(desdeNuevoTitular){
            daoTitular.save(nuevoTitular);
            System.out.print("Se guardo bien el titular!");
            }
        }
        catch(DataAccessLayerException e){
            System.out.print(e);
        }
        finally{
            try{
                daoLicencia.save(nuevaLicencia);
                System.out.print("Se guardo bien la licencia!");
                GestorLicencias.imprimirLicencia(nuevaLicencia);
                JOptionPane.showMessageDialog(null, "El nuevo titular y la nueva licencia se han guardado correctamente");
                GestionLicencias pantalla = new GestionLicencias();
                pantalla.setVisible(true);
                dispose();
            }
            catch(DataAccessLayerException e){
                System.out.print(e);
            }
        }
        
    }                                                     

    private void txt_observacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_observacionesKeyTyped
        //se limita a 500 caracteres el campo observaciones
        if (txt_observaciones.getText().length()>= 500){

        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"Alcanzo el maximo de caracteres (500 caracteres)");
        }
    }//GEN-LAST:event_txt_observacionesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmitirLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmitirLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmitirLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmitirLicencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmitirLicencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_atras;
    private javax.swing.JButton boton_emitir_licencia;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_centro;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> listaClase;
    private javax.swing.JComboBox<String> listaDonante;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_direccion;
    private javax.swing.JLabel txt_factor_sanguineo;
    private javax.swing.JLabel txt_fecha_nac;
    private javax.swing.JLabel txt_grupo_sanguineo;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_nombre_user;
    private javax.swing.JLabel txt_nro_doc;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JLabel txt_tipo_doc;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
