package Pantallas;

import Entidades.Administrativo;
import Gestores.GestorAdministrativo;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Juan Ignacio de la Iglesia
 */
public class GestionAdministrativos extends javax.swing.JFrame {

    TablaModeloAdministrativo modeloTabla = new TablaModeloAdministrativo();
    
    public GestionAdministrativos() {
        initComponents();
        setTitle("Gestión");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        tabla.setModel(modeloTabla);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_superior3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_centro = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        boton_buscar = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        boton_modificar_administrativo = new javax.swing.JButton();
        boton_nuevo_administrativo = new javax.swing.JButton();
        jPanel_inferior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        boton_atras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_mensaje_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior3.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior3.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior3.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel5.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Usuario: ");
        jLabel11.setMaximumSize(new java.awt.Dimension(100, 60));
        jLabel11.setMinimumSize(new java.awt.Dimension(100, 60));
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel7.add(jLabel11);

        txt_user.setText("jLabel9");
        txt_user.setMaximumSize(new java.awt.Dimension(125, 60));
        txt_user.setMinimumSize(new java.awt.Dimension(125, 60));
        txt_user.setPreferredSize(new java.awt.Dimension(125, 60));
        jPanel7.add(txt_user);

        jPanel5.add(jPanel7);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Nombre:");
        jLabel18.setMaximumSize(new java.awt.Dimension(100, 60));
        jLabel18.setMinimumSize(new java.awt.Dimension(100, 60));
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel6.add(jLabel18);

        txt_nombre_user.setText("jLabel9");
        txt_nombre_user.setMaximumSize(new java.awt.Dimension(125, 60));
        txt_nombre_user.setMinimumSize(new java.awt.Dimension(125, 60));
        txt_nombre_user.setPreferredSize(new java.awt.Dimension(125, 60));
        jPanel6.add(txt_nombre_user);

        jPanel5.add(jPanel6);

        jPanel_superior3.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(750, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(750, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 120));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestión de Licencias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 189, 39, 190);
        jPanel4.add(jLabel4, gridBagConstraints);

        jPanel_superior3.add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel_superior3.add(jPanel3);

        getContentPane().add(jPanel_superior3);

        jPanel_centro.setLayout(new javax.swing.BoxLayout(jPanel_centro, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(1280, 50));
        jPanel9.setMinimumSize(new java.awt.Dimension(1280, 50));
        jPanel9.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel10.add(jLabel2);

        txt_apellido.setMaximumSize(new java.awt.Dimension(175, 35));
        txt_apellido.setMinimumSize(new java.awt.Dimension(175, 35));
        txt_apellido.setPreferredSize(new java.awt.Dimension(175, 35));
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyPressed(evt);
            }
        });
        jPanel10.add(txt_apellido);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Apellido:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel10.add(jLabel1);

        txt_nombre.setMaximumSize(new java.awt.Dimension(175, 35));
        txt_nombre.setMinimumSize(new java.awt.Dimension(175, 35));
        txt_nombre.setPreferredSize(new java.awt.Dimension(175, 35));
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        jPanel10.add(txt_nombre);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DNI:");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel10.add(jLabel3);

        txt_dni.setMaximumSize(new java.awt.Dimension(175, 35));
        txt_dni.setMinimumSize(new java.awt.Dimension(175, 35));
        txt_dni.setPreferredSize(new java.awt.Dimension(175, 35));
        txt_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dniKeyPressed(evt);
            }
        });
        jPanel10.add(txt_dni);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        boton_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_buscarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 171, 11, 172);
        jPanel11.add(boton_buscar, gridBagConstraints);

        jPanel9.add(jPanel11);

        jPanel_centro.add(jPanel9);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(tabla);

        jPanel_centro.add(jScrollPane13);

        jPanel8.setMaximumSize(new java.awt.Dimension(1280, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(1280, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        boton_modificar_administrativo.setText("Modificar Administrativo");
        boton_modificar_administrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificar_administrativoActionPerformed(evt);
            }
        });
        boton_modificar_administrativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_modificar_administrativoKeyPressed(evt);
            }
        });
        jPanel8.add(boton_modificar_administrativo, new java.awt.GridBagConstraints());

        boton_nuevo_administrativo.setText(" Nuevo Administrativo");
        boton_nuevo_administrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevo_administrativoActionPerformed(evt);
            }
        });
        jPanel8.add(boton_nuevo_administrativo, new java.awt.GridBagConstraints());

        jPanel_centro.add(jPanel8);

        getContentPane().add(jPanel_centro);

        jPanel_inferior.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(440, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(440, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(440, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        boton_atras.setText("Atras");
        boton_atras.setMaximumSize(new java.awt.Dimension(250, 50));
        boton_atras.setMinimumSize(new java.awt.Dimension(250, 50));
        boton_atras.setPreferredSize(new java.awt.Dimension(250, 50));
        boton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atrasActionPerformed(evt);
            }
        });
        boton_atras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_atrasKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 196, 36, 196);
        jPanel2.add(boton_atras, gridBagConstraints);

        jPanel_inferior.add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(840, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 100));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_mensaje_error.setForeground(new java.awt.Color(255, 0, 0));
        txt_mensaje_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mensaje_error.setMaximumSize(new java.awt.Dimension(840, 100));
        txt_mensaje_error.setMinimumSize(new java.awt.Dimension(840, 100));
        txt_mensaje_error.setPreferredSize(new java.awt.Dimension(840, 100));
        jPanel1.add(txt_mensaje_error);

        jPanel_inferior.add(jPanel1);

        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atrasActionPerformed
        Gestion obj = new Gestion();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_atrasActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        //borro resultados anteriores al hacer busquedas sucesivas
        limpiarTabla(tabla, modeloTabla);
        txt_mensaje_error.setText("");
        //obtengo los datos ingresados en los filtros de busqueda
        String nombre = txt_nombre.getText();    
        String apellido = txt_apellido.getText();
        String dni = txt_dni.getText();
        
        GestorAdministrativo gestorAdministrativo = GestorAdministrativo.getInstance(); //se pide la instancia de GestorAdministrativo
        List<Administrativo> listaAdministrativo= new ArrayList<Administrativo>();
        if("".equals(nombre) && "".equals(apellido) && "".equals(dni)){ //no completo al menos un criterio de busqueda, se buscan todos los administrativos  
            listaAdministrativo = gestorAdministrativo.buscarAdministrativos();  //busca en la BS y pasa una lista con TODOS los administrativos
            modeloTabla.addAllAdministrativos(listaAdministrativo);
        }
        else{
            listaAdministrativo = gestorAdministrativo.buscarAdministrativos(nombre, apellido, dni);  //busca en la BS y pasa una lista con los administrativos filtrados
            modeloTabla.addAllAdministrativos(listaAdministrativo);
        }
       
        if(modeloTabla.getAdministrativos().size()==0)
            txt_mensaje_error.setText("No se encontraron registros");
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_buscarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void txt_apellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_buscarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_apellidoKeyPressed

    private void txt_dniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_buscarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_dniKeyPressed

    private void boton_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_buscarActionPerformed(null);
        }
    }//GEN-LAST:event_boton_buscarKeyPressed

    private void boton_atrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_atrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_atrasActionPerformed(null);
        }
    }//GEN-LAST:event_boton_atrasKeyPressed

    private void boton_modificar_administrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificar_administrativoActionPerformed
        Integer filaSeleccionada= tabla.getSelectedRow();
       //si no hay una fila seleccionada filaSeleccionada= -1 por default
        if (filaSeleccionada != -1) {
            Administrativo administrativo = modeloTabla.getAdministrativo(tabla.getSelectedRow());
            ModificarAdministrativo obj = new ModificarAdministrativo(administrativo);
            obj.setVisible(true);
            dispose();
       }
        else{
            txt_mensaje_error.setText("Seleccione el administrador al cual desea modificar"); 
        }
    }//GEN-LAST:event_boton_modificar_administrativoActionPerformed

    private void boton_modificar_administrativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_modificar_administrativoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_modificar_administrativoKeyPressed

    private void boton_nuevo_administrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevo_administrativoActionPerformed
        NuevoAdministrativo obj = new NuevoAdministrativo();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_nuevo_administrativoActionPerformed

    private void limpiarTabla(JTable tabla, TablaModeloAdministrativo modeloTabla){
       modeloTabla.deleteAllAdministrativos();
    }
    
    public class TablaModeloAdministrativo extends AbstractTableModel {

    private String[] columnNames = {"Nombre", "Apellido","DNI"};
    private List<Administrativo> data = new ArrayList<Administrativo>();

    public void addAdministrativo(Administrativo administrativo) {
        data.add(administrativo);
        fireTableDataChanged();
    }
    
     public void addAllAdministrativos(List<Administrativo> administrativo ) {
        data.addAll(administrativo);
        fireTableDataChanged();
    }

    public void deleteAdministrativo(int rowIndex) {
        data.remove(rowIndex);
        fireTableDataChanged();
    }
    
    public void deleteAllAdministrativos() {
        data.clear();
        fireTableDataChanged();
    }

    @Override
    public String getColumnName(int columnIndex) {
        return columnNames[columnIndex];
    }

    @Override
    public int getRowCount() {
        return data.size();
    }

    @Override
    public int getColumnCount() {
        return 3;
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        switch (columnIndex) {
            case 0:
                return data.get(rowIndex).getNombre();
            case 1:
                return data.get(rowIndex).getApellido();
            case 2:
                return data.get(rowIndex).getDni();
            default:
                return null;
        }
    }
    
    public Administrativo getAdministrativo(int fila) {
            return (Administrativo) data.get(fila);
        }

    @Override
    public Class getColumnClass(int columnIndex) {
//        return getValueAt(0, columnIndex).getClass();
        return String.class;
    }

    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return false;
    }

    @Override
    public void setValueAt(Object value, int rowIndex, int columnIndex) {
        
    }
    
    public List<Administrativo> getAdministrativos() {
            return data;
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAdministrativos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_atras;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_modificar_administrativo;
    private javax.swing.JButton boton_nuevo_administrativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_centro;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior3;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JLabel txt_mensaje_error;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_nombre_user;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}