package Pantallas;

import Entidades.Titular;
import Gestores.GestorAdministrativo;
import PlantillasDePantallas.*;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

/**
 *
 * @author Juan Ignacio de la Iglesia
 */
public class Gestion extends javax.swing.JFrame {

    public Gestion() {
        initComponents();
        setTitle("Gestión");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        if(GestorAdministrativo.getInstance().getAdministrativo().getSuperuser()==0)
            boton_usuarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel_centro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        boton_licencias = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10));
        jButton4 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10));
        boton_listados = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10));
        boton_usuarios = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10), new java.awt.Dimension(400, 10));
        boton_salir_sistema = new javax.swing.JButton();
        jPanel_inferior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(300, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel8.setText("Usuario: ");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel3.add(jLabel8);

        txt_user.setText("jLabel9");
        txt_user.setMaximumSize(new java.awt.Dimension(130, 60));
        txt_user.setMinimumSize(new java.awt.Dimension(130, 60));
        txt_user.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel3.add(txt_user);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel15.setText("Nombre:");
        jLabel15.setMaximumSize(new java.awt.Dimension(100, 60));
        jLabel15.setMinimumSize(new java.awt.Dimension(100, 60));
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel4.add(jLabel15);

        txt_nombre_user.setText("jLabel9");
        txt_nombre_user.setMaximumSize(new java.awt.Dimension(130, 60));
        txt_nombre_user.setMinimumSize(new java.awt.Dimension(130, 60));
        txt_nombre_user.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel4.add(txt_nombre_user);

        jPanel1.add(jPanel4);

        jPanel_superior.add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(850, 120));
        jPanel2.setMinimumSize(new java.awt.Dimension(850, 120));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión");
        jLabel1.setMaximumSize(new java.awt.Dimension(750, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(750, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(750, 120));
        jPanel2.add(jLabel1);

        jPanel_superior.add(jPanel2);

        jPanel5.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel5);

        getContentPane().add(jPanel_superior);

        jPanel_centro.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setFocusCycleRoot(true);
        jPanel6.setFocusTraversalPolicyProvider(true);
        jPanel6.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        boton_licencias.setText("Licencias");
        boton_licencias.setAlignmentY(0.0F);
        boton_licencias.setMaximumSize(new java.awt.Dimension(400, 75));
        boton_licencias.setMinimumSize(new java.awt.Dimension(400, 75));
        boton_licencias.setPreferredSize(new java.awt.Dimension(400, 75));
        boton_licencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_licenciasActionPerformed(evt);
            }
        });
        boton_licencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_licenciasKeyPressed(evt);
            }
        });
        jPanel6.add(boton_licencias);

        filler1.setAlignmentX(0.0F);
        filler1.setAlignmentY(0.0F);
        jPanel6.add(filler1);

        jButton4.setText("Titulares");
        jButton4.setAlignmentY(0.0F);
        jButton4.setMaximumSize(new java.awt.Dimension(400, 75));
        jButton4.setMinimumSize(new java.awt.Dimension(400, 75));
        jButton4.setPreferredSize(new java.awt.Dimension(400, 75));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);

        filler2.setAlignmentX(0.0F);
        filler2.setAlignmentY(0.0F);
        jPanel6.add(filler2);

        boton_listados.setText("Listados");
        boton_listados.setAlignmentY(0.0F);
        boton_listados.setMaximumSize(new java.awt.Dimension(400, 75));
        boton_listados.setMinimumSize(new java.awt.Dimension(400, 75));
        boton_listados.setPreferredSize(new java.awt.Dimension(400, 75));
        boton_listados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_listadosActionPerformed(evt);
            }
        });
        jPanel6.add(boton_listados);

        filler3.setAlignmentX(0.0F);
        filler3.setAlignmentY(0.0F);
        jPanel6.add(filler3);

        boton_usuarios.setText("Administración de Usuarios");
        boton_usuarios.setAlignmentY(0.0F);
        boton_usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_usuarios.setMaximumSize(new java.awt.Dimension(400, 75));
        boton_usuarios.setMinimumSize(new java.awt.Dimension(400, 75));
        boton_usuarios.setPreferredSize(new java.awt.Dimension(400, 75));
        boton_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_usuariosActionPerformed(evt);
            }
        });
        boton_usuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_usuariosKeyPressed(evt);
            }
        });
        jPanel6.add(boton_usuarios);

        filler4.setAlignmentX(0.0F);
        filler4.setAlignmentY(0.0F);
        jPanel6.add(filler4);

        boton_salir_sistema.setText("Abandonar el Sistema");
        boton_salir_sistema.setAlignmentY(0.0F);
        boton_salir_sistema.setMaximumSize(new java.awt.Dimension(400, 75));
        boton_salir_sistema.setMinimumSize(new java.awt.Dimension(400, 75));
        boton_salir_sistema.setPreferredSize(new java.awt.Dimension(400, 75));
        boton_salir_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salir_sistemaActionPerformed(evt);
            }
        });
        boton_salir_sistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_salir_sistemaKeyPressed(evt);
            }
        });
        jPanel6.add(boton_salir_sistema);

        jPanel_centro.add(jPanel6);

        getContentPane().add(jPanel_centro);

        jPanel_inferior.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boton_listadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_listadosActionPerformed
        ListaLicencias obj = new ListaLicencias();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_boton_listadosActionPerformed

    private void boton_licenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_licenciasActionPerformed
      
        GestionLicencias obj = new GestionLicencias();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_boton_licenciasActionPerformed

    private void boton_licenciasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_licenciasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_licenciasActionPerformed(null);
        }
    }//GEN-LAST:event_boton_licenciasKeyPressed

    private void boton_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_usuariosActionPerformed
        GestionAdministrativos obj = new GestionAdministrativos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_usuariosActionPerformed

    private void boton_usuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_usuariosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_usuariosActionPerformed(null);
        }
    }//GEN-LAST:event_boton_usuariosKeyPressed

    private void boton_salir_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salir_sistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_salir_sistemaActionPerformed

    private void boton_salir_sistemaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_salir_sistemaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_salir_sistemaActionPerformed(null);
        }
    }//GEN-LAST:event_boton_salir_sistemaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);       
            }  
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_licencias;
    private javax.swing.JButton boton_listados;
    private javax.swing.JButton boton_salir_sistema;
    private javax.swing.JButton boton_usuarios;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_centro;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JLabel txt_nombre_user;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
