package Pantallas;

import Entidades.Administrativo;
import Entidades.Licencia;
import Entidades.Titular;
import Gestores.GestorAdministrativo;
import Gestores.GestorLicencias;
import java.applet.AudioClip;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Ignacio de la Iglesia
 */
public class Ingreso extends javax.swing.JFrame {

    public Ingreso() {
        initComponents();
        setTitle("Ingreso");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_centro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 125), new java.awt.Dimension(400, 125), new java.awt.Dimension(400, 125));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 225), new java.awt.Dimension(400, 225), new java.awt.Dimension(400, 225));
        jPanel_inferior = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boton_abandonar_sistema = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        boton_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel_superior.add(jLabel1);

        getContentPane().add(jPanel_superior);

        jPanel_centro.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel_centro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(filler2);

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 75));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 75));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel2.setText("Usuario:");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 75));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 75));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 75));
        jPanel2.add(jLabel2);

        txt_user.setMaximumSize(new java.awt.Dimension(300, 40));
        txt_user.setMinimumSize(new java.awt.Dimension(300, 40));
        txt_user.setPreferredSize(new java.awt.Dimension(300, 40));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
        });
        jPanel2.add(txt_user);

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 75));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 75));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 75));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel3.setText("Contraseña:");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 75));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 75));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 75));
        jPanel3.add(jLabel3);

        txt_pass.setFocusAccelerator('\u25cf');
        txt_pass.setFocusCycleRoot(true);
        txt_pass.setMaximumSize(new java.awt.Dimension(300, 40));
        txt_pass.setMinimumSize(new java.awt.Dimension(300, 40));
        txt_pass.setPreferredSize(new java.awt.Dimension(300, 40));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        jPanel3.add(txt_pass);

        jPanel1.add(jPanel3);
        jPanel1.add(filler1);

        jPanel_centro.add(jPanel1);

        getContentPane().add(jPanel_centro);

        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 100));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        boton_abandonar_sistema.setText("Abandonar el Sistema");
        boton_abandonar_sistema.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_abandonar_sistema.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_abandonar_sistema.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_abandonar_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_abandonar_sistemaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 220, 25, 220);
        jPanel5.add(boton_abandonar_sistema, gridBagConstraints);

        jPanel_inferior.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(640, 100));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        boton_ingresar.setText("Ingresar");
        boton_ingresar.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_ingresar.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_ingresar.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ingresarActionPerformed(evt);
            }
        });
        boton_ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_ingresarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 220, 25, 220);
        jPanel4.add(boton_ingresar, gridBagConstraints);

        jPanel_inferior.add(jPanel4);

        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_abandonar_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_abandonar_sistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_abandonar_sistemaActionPerformed

    private void boton_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ingresarActionPerformed
        GestorAdministrativo gestorAdministrativo = GestorAdministrativo.getInstance();

        String password = new String(txt_pass.getPassword());
        String user2 = new String(txt_user.getText());

        int validacion = gestorAdministrativo.validarAdministrativo(user2, password);
       
        if (validacion==1) {
            //si el campo user_nuevo == 1 abrimos un pop up que permite cambiar la contraseña antes de ingresar al sistema
            if(GestorAdministrativo.getInstance().getAdministrativo().getUser_nuevo()== 1){
                txt_pass.setText("");
                txt_pass.requestFocus();
                PopUpCambioPass obj = new PopUpCambioPass();
                obj.setVisible(true);
            }
            else{
                Gestion obj = new Gestion();
                obj.setVisible(true);
                dispose();
            }
        } else {
             /*AudioClip sonido;
                sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/error2.wav"));
                sonido.play();
            */
            JOptionPane.showMessageDialog(null, "El usuario o la contraseña no son válidos", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
            txt_user.setText("");
            txt_pass.setText("");
            txt_user.requestFocus();
        }
    }//GEN-LAST:event_boton_ingresarActionPerformed

    private void boton_ingresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_ingresarKeyPressed
        //da al enter la misma accion que el click
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_ingresarActionPerformed(null);
        }
    }//GEN-LAST:event_boton_ingresarKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_ingresarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            boton_ingresarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_abandonar_sistema;
    private javax.swing.JButton boton_ingresar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_centro;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
