/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Dao.DaoLicencia;
import Dao.DaoTitular;
import Entidades.Licencia;
import Entidades.Titular;
import Entidades.TitularAuxParaTabla;
import Gestores.GestorAdministrativo;
import Gestores.GestorLicencias;
import Gestores.GestorTitular;
import com.mysql.jdbc.StringUtils;
import static java.lang.System.console;
import java.sql.Date;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
/**
 *
 * @author PC
 */
import static java.lang.System.console;
public class ListaLicencias extends javax.swing.JFrame {
    TablaModeloTitular modeloTabla = new TablaModeloTitular();
    /**
     * Creates new form ListaLicencias
     */
    public ListaLicencias() {
        initComponents();
        setTitle("Listado de Licencias");
        setLocationRelativeTo(null);
        lb_username.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        lb_nombre.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        tabla_licencias_filtradas.setModel(modeloTabla);
        tabla_licencias_filtradas.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lb_titulo_username = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lb_titulo_nombre = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb_titulo_pantalla = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        txt_nombre_titutal = new javax.swing.JLabel();
        input_nombre_titular = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        txt_apellido_titular = new javax.swing.JLabel();
        input_apellido_titular = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        txt_grupo_sanguineo = new javax.swing.JLabel();
        cb_grupo_sanguineo = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        txt_factor_rh = new javax.swing.JLabel();
        cb_factor_rh = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        txt_donante = new javax.swing.JLabel();
        cb_donante = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        txt_criterios_busqueda = new javax.swing.JLabel();
        cb_vigencia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_licencias_filtradas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btn_atras = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btn_filtrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel5.setMaximumSize(new java.awt.Dimension(250, 660));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 660));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(250, 600));
        jPanel7.setMinimumSize(new java.awt.Dimension(250, 600));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        lb_titulo_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_titulo_username.setText("Usuario:");
        lb_titulo_username.setMaximumSize(new java.awt.Dimension(100, 60));
        lb_titulo_username.setMinimumSize(new java.awt.Dimension(100, 60));
        lb_titulo_username.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel7.add(lb_titulo_username);
        lb_titulo_username.getAccessibleContext().setAccessibleDescription("");

        lb_username.setMaximumSize(new java.awt.Dimension(130, 60));
        lb_username.setMinimumSize(new java.awt.Dimension(130, 60));
        lb_username.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel7.add(lb_username);

        jPanel5.add(jPanel7);

        jPanel8.setMaximumSize(new java.awt.Dimension(250, 60));
        jPanel8.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        lb_titulo_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_titulo_nombre.setText("Nombre:");
        lb_titulo_nombre.setMaximumSize(new java.awt.Dimension(100, 60));
        lb_titulo_nombre.setMinimumSize(new java.awt.Dimension(100, 60));
        lb_titulo_nombre.setPreferredSize(new java.awt.Dimension(100, 60));
        lb_titulo_nombre.setRequestFocusEnabled(false);
        jPanel8.add(lb_titulo_nombre);

        lb_nombre.setMaximumSize(new java.awt.Dimension(130, 60));
        lb_nombre.setMinimumSize(new java.awt.Dimension(130, 60));
        lb_nombre.setPreferredSize(new java.awt.Dimension(130, 60));
        jPanel8.add(lb_nombre);

        jPanel5.add(jPanel8);

        jPanel1.add(jPanel5);

        jPanel3.setToolTipText("");
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(750, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(750, 120));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(750, 120));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        lb_titulo_pantalla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_titulo_pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo_pantalla.setText("Listado de Licencias");
        lb_titulo_pantalla.setToolTipText("");
        lb_titulo_pantalla.setAlignmentY(0.0F);
        lb_titulo_pantalla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_titulo_pantalla.setMaximumSize(new java.awt.Dimension(500, 120));
        lb_titulo_pantalla.setMinimumSize(new java.awt.Dimension(500, 120));
        lb_titulo_pantalla.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel3.add(lb_titulo_pantalla);

        jPanel1.add(jPanel3);

        jPanel6.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel6.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(1280, 75));
        jPanel9.setMinimumSize(new java.awt.Dimension(1280, 75));
        jPanel9.setPreferredSize(new java.awt.Dimension(1280, 75));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel16.setMaximumSize(new java.awt.Dimension(300, 75));
        jPanel16.setMinimumSize(new java.awt.Dimension(300, 75));
        jPanel16.setPreferredSize(new java.awt.Dimension(300, 75));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jPanel18.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel18.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel18.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_nombre_titutal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_nombre_titutal.setText("Nombre:");
        txt_nombre_titutal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        txt_nombre_titutal.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_nombre_titutal.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_nombre_titutal.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel18.add(txt_nombre_titutal);

        input_nombre_titular.setMaximumSize(new java.awt.Dimension(185, 35));
        input_nombre_titular.setMinimumSize(new java.awt.Dimension(185, 35));
        input_nombre_titular.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel18.add(input_nombre_titular);

        jPanel16.add(jPanel18);

        jPanel19.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel19.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel19.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_apellido_titular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_apellido_titular.setText("Apellido:");
        txt_apellido_titular.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_apellido_titular.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_apellido_titular.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel19.add(txt_apellido_titular);

        input_apellido_titular.setMaximumSize(new java.awt.Dimension(185, 35));
        input_apellido_titular.setMinimumSize(new java.awt.Dimension(185, 35));
        input_apellido_titular.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel19.add(input_apellido_titular);

        jPanel16.add(jPanel19);

        jPanel9.add(jPanel16);

        jPanel21.setMaximumSize(new java.awt.Dimension(300, 75));
        jPanel21.setMinimumSize(new java.awt.Dimension(300, 75));
        jPanel21.setPreferredSize(new java.awt.Dimension(300, 75));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.Y_AXIS));

        jPanel22.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel22.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel22.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_grupo_sanguineo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_grupo_sanguineo.setText("Grupo:");
        txt_grupo_sanguineo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        txt_grupo_sanguineo.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_grupo_sanguineo.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_grupo_sanguineo.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel22.add(txt_grupo_sanguineo);

        cb_grupo_sanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indiferente", "0", "A", "B", "AB" }));
        cb_grupo_sanguineo.setMaximumSize(new java.awt.Dimension(185, 35));
        cb_grupo_sanguineo.setMinimumSize(new java.awt.Dimension(185, 35));
        cb_grupo_sanguineo.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel22.add(cb_grupo_sanguineo);

        jPanel21.add(jPanel22);

        jPanel23.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel23.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel23.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_factor_rh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_factor_rh.setText("Factor RH:");
        txt_factor_rh.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_factor_rh.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_factor_rh.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel23.add(txt_factor_rh);

        cb_factor_rh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indiferente", "+", "-" }));
        cb_factor_rh.setMaximumSize(new java.awt.Dimension(185, 35));
        cb_factor_rh.setMinimumSize(new java.awt.Dimension(185, 35));
        cb_factor_rh.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel23.add(cb_factor_rh);

        jPanel21.add(jPanel23);

        jPanel9.add(jPanel21);

        jPanel17.setMaximumSize(new java.awt.Dimension(300, 75));
        jPanel17.setMinimumSize(new java.awt.Dimension(300, 75));
        jPanel17.setPreferredSize(new java.awt.Dimension(300, 75));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel25.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel25.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_donante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_donante.setText("Es donante:");
        txt_donante.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_donante.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_donante.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel25.add(txt_donante);

        cb_donante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indiferente", "Si", "No" }));
        cb_donante.setMaximumSize(new java.awt.Dimension(185, 35));
        cb_donante.setMinimumSize(new java.awt.Dimension(185, 35));
        cb_donante.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel25.add(cb_donante);

        jPanel17.add(jPanel25);

        jPanel10.setMaximumSize(new java.awt.Dimension(300, 37));
        jPanel10.setMinimumSize(new java.awt.Dimension(300, 37));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 37));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_criterios_busqueda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_criterios_busqueda.setText("Licencias Vig/Exp:");
        txt_criterios_busqueda.setMaximumSize(new java.awt.Dimension(90, 37));
        txt_criterios_busqueda.setMinimumSize(new java.awt.Dimension(90, 37));
        txt_criterios_busqueda.setPreferredSize(new java.awt.Dimension(90, 37));
        jPanel10.add(txt_criterios_busqueda);

        cb_vigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambas", "Solo Vigentes", "Solo Expiradas" }));
        cb_vigencia.setMaximumSize(new java.awt.Dimension(185, 35));
        cb_vigencia.setMinimumSize(new java.awt.Dimension(185, 35));
        cb_vigencia.setPreferredSize(new java.awt.Dimension(185, 35));
        jPanel10.add(cb_vigencia);

        jPanel17.add(jPanel10);

        jPanel9.add(jPanel17);

        jPanel2.add(jPanel9);

        tabla_licencias_filtradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Clase", "Grupo Sanguineo", "Factor RH", "Donante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_licencias_filtradas);

        jPanel2.add(jScrollPane1);

        jPanel4.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel11.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel11.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel11.setPreferredSize(new java.awt.Dimension(640, 100));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel13.setMaximumSize(new java.awt.Dimension(200, 100));
        jPanel13.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        btn_atras.setText("Atras");
        btn_atras.setMaximumSize(new java.awt.Dimension(200, 50));
        btn_atras.setMinimumSize(new java.awt.Dimension(200, 50));
        btn_atras.setPreferredSize(new java.awt.Dimension(200, 50));
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        jPanel13.add(btn_atras, new java.awt.GridBagConstraints());

        jPanel11.add(jPanel13);

        jPanel4.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(640, 100));
        jPanel12.setMinimumSize(new java.awt.Dimension(640, 100));
        jPanel12.setPreferredSize(new java.awt.Dimension(640, 100));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel14.setMaximumSize(new java.awt.Dimension(200, 100));
        jPanel14.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        btn_filtrar.setText("Filtrar");
        btn_filtrar.setMaximumSize(new java.awt.Dimension(200, 50));
        btn_filtrar.setMinimumSize(new java.awt.Dimension(200, 50));
        btn_filtrar.setPreferredSize(new java.awt.Dimension(200, 50));
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });
        jPanel14.add(btn_filtrar, new java.awt.GridBagConstraints());

        jPanel12.add(jPanel14);

        jPanel4.add(jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
        //<-------------------------------------------------------------------->
        /*
        limpiarTabla(tabla_licencias_filtradas, modeloTabla);
        txt_mensaje_error.setText("");
        
                
        String nombre = input_nombre_titular.getText();    
        String apellido = input_apellido_titular.getText();
        String grupo_sanguineo = (String)cb_grupo_sanguineo.getSelectedItem();
        String factor_sanguineo = (String)cb_factor_rh.getSelectedItem();
        String donante = (String)cb_donante.getSelectedItem();
        
        GestorLicencias gestorLicencia = GestorLicencias.getInstance(); //se pide la instancia de GestorAdministrativo
        List<Licencia> listaLicencias= new ArrayList<Licencia>();
        if("".equals(nombre) && "".equals(apellido) && "".equals(grupo_sanguineo) && "".equals(factor_sanguineo) && "".equals(donante)){
            listaLicencias = gestorLicencia.buscarLicencias();
            modeloTabla.addAllTitulares(listaLicencias);
        }
        else{
            listaLicencias = gestorLicencia.buscarLicencias(nombre,apellido,grupo_sanguineo,factor_sanguineo,donante);
            modeloTabla.addAllTitulares(listaLicencias);
        }*/
        //<--------------------------------------------------------------------->
        
        List licencias = new ArrayList();
        int codigoFiltrado = 0;
        ArrayList<String> arregloParametros = new ArrayList<>();
        
        limpiarTabla(tabla_licencias_filtradas, modeloTabla);
        
        String vigencia = (cb_vigencia.getSelectedItem().toString().equals("Ambas")) ? null : cb_vigencia.getSelectedItem().toString();
        String nombreTitular = (StringUtils.isNullOrEmpty(input_nombre_titular.getText())) ? null : input_nombre_titular.getText();
        String apellidoTitular = (StringUtils.isNullOrEmpty(input_apellido_titular.getText())) ? null : input_apellido_titular.getText();
        String grupoSanguineo = (cb_grupo_sanguineo.getSelectedItem().toString().equals("Indiferente")) ? null : cb_grupo_sanguineo.getSelectedItem().toString();
        String factorRH = (cb_factor_rh.getSelectedItem().toString().equals("Indiferente")) ? null : cb_factor_rh.getSelectedItem().toString();
        String esDonante = (cb_donante.getSelectedItem().toString().equals("Indiferente")) ? null : cb_donante.getSelectedItem().toString();
        
        arregloParametros.add(0, nombreTitular);
        arregloParametros.add(1, apellidoTitular);
        arregloParametros.add(2, grupoSanguineo);
        arregloParametros.add(3, factorRH);
        arregloParametros.add(4, esDonante);
        arregloParametros.add(5, vigencia);
        
        GestorLicencias gestorLicencias = new GestorLicencias(); //se pide la instancia de GestorTitular
        
        System.out.print(arregloParametros.toString());
        
        licencias = gestorLicencias.buscarTitulares(codigoFiltrado, arregloParametros);
        
        modeloTabla.addAllTitulares(licencias);
    }//GEN-LAST:event_btn_filtrarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        Gestion obj = new Gestion();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed
    
    private void limpiarTabla(JTable tabla, ListaLicencias.TablaModeloTitular modeloTabla){
       modeloTabla.deleteAllTitulares();
    }
   
    public class TablaModeloTitular extends javax.swing.table.AbstractTableModel {

    private String[] columnNames = {"Nombre", "Apellido", "DNI", "Clase", "Grupo Sanguineo", "Factor RH", "Donante", "Fecha de Vencimiento"};
    private List<TitularAuxParaTabla> data = new ArrayList<TitularAuxParaTabla>();

    public void addTitular(TitularAuxParaTabla titularAuxParaTabla) {
        data.add(titularAuxParaTabla);
        fireTableDataChanged();
    }
    
     public void addAllTitulares(List<TitularAuxParaTabla> listaTitularAuxParaTabla ) {
        data.addAll(listaTitularAuxParaTabla);
        fireTableDataChanged();
    }

    public void deleteTitular(int rowIndex) {
        data.remove(rowIndex);
        fireTableDataChanged();
    }
    
    public void deleteAllTitulares() {
        data.clear();
        fireTableDataChanged();
    }

    @Override
    public String getColumnName(int columnIndex) {
        return columnNames[columnIndex];
    }

    @Override
    public int getRowCount() {
        return data.size();
    }

    @Override
    public int getColumnCount() {
        return 8;
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        switch (columnIndex) {
            case 0:
                return data.get(rowIndex).getTitularOriginal().getNombre();
            case 1:
                return data.get(rowIndex).getTitularOriginal().getApellido();
            case 2:
                return data.get(rowIndex).getTitularOriginal().getDni();
            case 3:
                if(data.get(rowIndex).getLicencia() == null)
                    return " ";
                else
                    return data.get(rowIndex).getLicencia().getClase();
            case 4:
                return data.get(rowIndex).getTitularOriginal().getGrupoSanguineo();
            case 5:
                return data.get(rowIndex).getTitularOriginal().getFactorSanguineo();
            case 6: 
                if(data.get(rowIndex).getLicencia() == null)
                    return " ";
                else
                return data.get(rowIndex).getLicencia().getDonante();
            case 7:
                if(data.get(rowIndex).getLicencia() == null)
                    return " ";
                else
                return data.get(rowIndex).getLicencia().getFechaVenc();
            default:
                return null;
        }
    }

   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaLicencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JComboBox<String> cb_donante;
    private javax.swing.JComboBox<String> cb_factor_rh;
    private javax.swing.JComboBox<String> cb_grupo_sanguineo;
    private javax.swing.JComboBox<String> cb_vigencia;
    private javax.swing.JTextField input_apellido_titular;
    private javax.swing.JTextField input_nombre_titular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_titulo_nombre;
    private javax.swing.JLabel lb_titulo_pantalla;
    private javax.swing.JLabel lb_titulo_username;
    private javax.swing.JLabel lb_username;
    private javax.swing.JTable tabla_licencias_filtradas;
    private javax.swing.JLabel txt_apellido_titular;
    private javax.swing.JLabel txt_criterios_busqueda;
    private javax.swing.JLabel txt_donante;
    private javax.swing.JLabel txt_factor_rh;
    private javax.swing.JLabel txt_grupo_sanguineo;
    private javax.swing.JLabel txt_nombre_titutal;
    // End of variables declaration//GEN-END:variables
}
