package Pantallas;

import Entidades.Administrativo;
import Gestores.GestorAdministrativo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Ignacio de la Iglesia
 */
public class ModificarAdministrativo extends javax.swing.JFrame {
    Administrativo administrativo_aux;
    //pido la instancia de gestor de administrativos
    GestorAdministrativo gestorAdministrativo = GestorAdministrativo.getInstance();
    
    public ModificarAdministrativo() {
  
    }
    
    public ModificarAdministrativo(Administrativo administrativo) {
        administrativo_aux = administrativo; 
        initComponents();
        setTitle("Modificar Administrativo");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
   
        //se setean los datos no modificables (datos del administrativo)
        txt_nombre.setText((String.valueOf(administrativo.getNombre())));
        txt_apellido.setText((String.valueOf(administrativo.getApellido())));
        txt_nro_doc.setText((String.valueOf(administrativo.getDni())));
        txt_nombre_usuario.setText((String.valueOf(administrativo.getUsername())));
        txt_pass.setText((String.valueOf(administrativo.getPassword())));
        int check = administrativo.getSuperuser();
 
        if(check == 1)
            checkBox_superuser.setSelected(true);
        else
            checkBox_superuser.setSelected(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_superior = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 60), new java.awt.Dimension(0, 60), new java.awt.Dimension(0, 60));
        jPanel12 = new javax.swing.JPanel();
        txt_titulo_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        txt_titulo_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        txt_titulo_num_doc = new javax.swing.JLabel();
        txt_nro_doc = new javax.swing.JFormattedTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 140), new java.awt.Dimension(0, 140), new java.awt.Dimension(0, 140));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 500), new java.awt.Dimension(100, 500), new java.awt.Dimension(100, 500));
        jPanel10 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 60), new java.awt.Dimension(0, 60), new java.awt.Dimension(0, 60));
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_usuario = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JFormattedTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        checkBox_superuser = new javax.swing.JCheckBox();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 140), new java.awt.Dimension(0, 140), new java.awt.Dimension(0, 140));
        jPanel_inferior = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        boton_atras = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txt_mensaje_error = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        boton_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel4.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Usuario: ");
        jLabel8.setMaximumSize(new java.awt.Dimension(75, 60));
        jLabel8.setMinimumSize(new java.awt.Dimension(75, 60));
        jLabel8.setPreferredSize(new java.awt.Dimension(75, 60));
        jPanel6.add(jLabel8);

        txt_user.setText("jLabel9");
        txt_user.setMaximumSize(new java.awt.Dimension(140, 60));
        txt_user.setMinimumSize(new java.awt.Dimension(140, 60));
        txt_user.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel6.add(txt_user);

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nombre:");
        jLabel15.setMaximumSize(new java.awt.Dimension(75, 60));
        jLabel15.setMinimumSize(new java.awt.Dimension(75, 60));
        jLabel15.setPreferredSize(new java.awt.Dimension(75, 60));
        jPanel5.add(jLabel15);

        txt_nombre_user.setText("jLabel9");
        txt_nombre_user.setMaximumSize(new java.awt.Dimension(140, 60));
        txt_nombre_user.setMinimumSize(new java.awt.Dimension(140, 60));
        txt_nombre_user.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel5.add(txt_nombre_user);

        jPanel4.add(jPanel5);

        jPanel_superior.add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(750, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(750, 120));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(750, 120));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Administrativo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 155, 39, 155);
        jPanel3.add(jLabel1, gridBagConstraints);

        jPanel_superior.add(jPanel3);

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel1);

        getContentPane().add(jPanel_superior);

        jPanel2.setBorder(null);
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel11.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel11.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        jPanel11.add(filler2);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        txt_titulo_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_titulo_nombre.setText("Nombre:");
        txt_titulo_nombre.setMaximumSize(new java.awt.Dimension(150, 100));
        txt_titulo_nombre.setMinimumSize(new java.awt.Dimension(150, 100));
        txt_titulo_nombre.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel12.add(txt_titulo_nombre);

        txt_nombre.setMaximumSize(new java.awt.Dimension(250, 35));
        txt_nombre.setMinimumSize(new java.awt.Dimension(250, 35));
        txt_nombre.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel12.add(txt_nombre);

        jPanel11.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        txt_titulo_apellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_titulo_apellido.setText("Apellido:");
        txt_titulo_apellido.setMaximumSize(new java.awt.Dimension(150, 100));
        txt_titulo_apellido.setMinimumSize(new java.awt.Dimension(150, 100));
        txt_titulo_apellido.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel13.add(txt_titulo_apellido);

        txt_apellido.setMaximumSize(new java.awt.Dimension(250, 35));
        txt_apellido.setMinimumSize(new java.awt.Dimension(250, 35));
        txt_apellido.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel13.add(txt_apellido);

        jPanel11.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        txt_titulo_num_doc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_titulo_num_doc.setText("DNI:");
        txt_titulo_num_doc.setMaximumSize(new java.awt.Dimension(150, 100));
        txt_titulo_num_doc.setMinimumSize(new java.awt.Dimension(150, 100));
        txt_titulo_num_doc.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel14.add(txt_titulo_num_doc);

        try {
            txt_nro_doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_nro_doc.setMaximumSize(new java.awt.Dimension(250, 35));
        txt_nro_doc.setMinimumSize(new java.awt.Dimension(250, 35));
        txt_nro_doc.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel14.add(txt_nro_doc);

        jPanel11.add(jPanel14);
        jPanel11.add(filler3);

        jPanel2.add(jPanel11);
        jPanel2.add(filler1);

        jPanel10.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel10.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));
        jPanel10.add(filler4);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre de usuario:");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel15.add(jLabel2);

        txt_nombre_usuario.setMaximumSize(new java.awt.Dimension(250, 35));
        txt_nombre_usuario.setMinimumSize(new java.awt.Dimension(250, 35));
        txt_nombre_usuario.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel15.add(txt_nombre_usuario);

        jPanel10.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña:");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 100));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel16.add(jLabel4);

        try {
            txt_pass.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_pass.setMaximumSize(new java.awt.Dimension(250, 35));
        txt_pass.setMinimumSize(new java.awt.Dimension(250, 35));
        txt_pass.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel16.add(txt_pass);

        jPanel10.add(jPanel16);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Superuser:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 100));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel17.add(jLabel3);

        checkBox_superuser.setMaximumSize(new java.awt.Dimension(250, 35));
        checkBox_superuser.setMinimumSize(new java.awt.Dimension(250, 35));
        checkBox_superuser.setPreferredSize(new java.awt.Dimension(250, 35));
        checkBox_superuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_superuserActionPerformed(evt);
            }
        });
        jPanel17.add(checkBox_superuser);

        jPanel10.add(jPanel17);
        jPanel10.add(filler5);

        jPanel2.add(jPanel10);

        getContentPane().add(jPanel2);

        jPanel_inferior.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel8.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        boton_atras.setText("Atras");
        boton_atras.setMaximumSize(new java.awt.Dimension(250, 50));
        boton_atras.setMinimumSize(new java.awt.Dimension(250, 50));
        boton_atras.setPreferredSize(new java.awt.Dimension(250, 50));
        boton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atrasActionPerformed(evt);
            }
        });
        boton_atras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_atrasKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 151, 36, 151);
        jPanel8.add(boton_atras, gridBagConstraints);

        jPanel_inferior.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        txt_mensaje_error.setForeground(new java.awt.Color(255, 0, 0));
        txt_mensaje_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mensaje_error.setMaximumSize(new java.awt.Dimension(480, 100));
        txt_mensaje_error.setMinimumSize(new java.awt.Dimension(480, 100));
        txt_mensaje_error.setPreferredSize(new java.awt.Dimension(480, 100));
        jPanel9.add(txt_mensaje_error);

        jPanel_inferior.add(jPanel9);

        jPanel7.setMaximumSize(new java.awt.Dimension(400, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        boton_modificar.setText("Modificar");
        boton_modificar.setMaximumSize(new java.awt.Dimension(250, 50));
        boton_modificar.setMinimumSize(new java.awt.Dimension(250, 50));
        boton_modificar.setPreferredSize(new java.awt.Dimension(250, 50));
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 136, 36, 137);
        jPanel7.add(boton_modificar, gridBagConstraints);

        jPanel_inferior.add(jPanel7);

        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atrasActionPerformed
        GestionAdministrativos obj = new GestionAdministrativos();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_boton_atrasActionPerformed

    private void boton_atrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_atrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_atrasActionPerformed(null);
        }
    }//GEN-LAST:event_boton_atrasKeyPressed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        txt_nombre.setBackground(java.awt.Color.WHITE);
        txt_apellido.setBackground(java.awt.Color.WHITE);
        txt_nro_doc.setBackground(java.awt.Color.WHITE);
            
             if(txt_nombre.getText().equals("")||txt_apellido.getText().equals("")||txt_nombre_usuario.getText().equals("")||txt_nro_doc.getText().equals("        ")||txt_pass.getText().equals("        ")){
                txt_mensaje_error.setText("Algunos campos se encuentran en blanco");
                if (txt_nombre.getText().equals("")){
                    txt_nombre.requestFocus();
                    txt_nombre.setBackground(java.awt.Color.RED);
                }
                if (txt_apellido.getText().equals("")){
                    txt_apellido.requestFocus();
                    txt_apellido.setBackground(java.awt.Color.RED);
                }
                
                if (txt_nombre_usuario.getText().equals("")){
                    txt_nombre_usuario.requestFocus();
                    txt_nombre_usuario.setBackground(java.awt.Color.RED);
                }
              
                if (txt_nro_doc.getText().equals("        ")){
                    txt_nro_doc.requestFocus();
                    txt_nro_doc.setBackground(java.awt.Color.red);
                }
                
                if (txt_pass.getText().equals("        ")){
                    txt_pass.requestFocus();
                    txt_pass.setBackground(java.awt.Color.red);
                }
             }
             else {
                 administrativo_aux.setNombre(txt_nombre.getText());
                 administrativo_aux.setApellido(txt_apellido.getText());
                 administrativo_aux.setDni(txt_nro_doc.getText());
                 administrativo_aux.setUsername(txt_nombre_usuario.getText());
                 administrativo_aux.setPassword(txt_pass.getText());
                 
                 if(checkBox_superuser.isSelected())
                     administrativo_aux.setSuperuser(1);
                 else administrativo_aux.setSuperuser(0);
                 
                 gestorAdministrativo.modificarAdministrativo(administrativo_aux);
     
                 JOptionPane.showMessageDialog(null, "El administrativo se ha modificado correctamente");
                 GestionAdministrativos obj = new GestionAdministrativos();
                 obj.setVisible(true);
                 dispose();
             }
                
        
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void checkBox_superuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_superuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_superuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_atras;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JCheckBox checkBox_superuser;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JLabel txt_mensaje_error;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_nombre_user;
    private javax.swing.JTextField txt_nombre_usuario;
    private javax.swing.JFormattedTextField txt_nro_doc;
    private javax.swing.JFormattedTextField txt_pass;
    private javax.swing.JLabel txt_titulo_apellido;
    private javax.swing.JLabel txt_titulo_nombre;
    private javax.swing.JLabel txt_titulo_num_doc;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
