package Pantallas;

import Entidades.Titular;
import Gestores.GestorAdministrativo;
import Gestores.GestorTitular;
import java.applet.AudioClip;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Juan Ignacio de la Iglesia
 */
public class ModificarTitular extends javax.swing.JFrame {
    Titular titular_aux;
    //pido la instancia de gestor de titular
    GestorTitular gestorTitular = GestorTitular.getInstance();
    
    public ModificarTitular() {
  
    }
    
    public ModificarTitular(Titular titular) {
        titular_aux = titular; 
        initComponents();
        setTitle("Modificar Titular");
        setLocationRelativeTo(null);
        //se pide al gestor y se muestra por pantalla los datos del administrativo registrado
        txt_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_user.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
   
        //se setean los datos no modificables (datos del titular)
        txt_nombre.setText((String.valueOf(titular.getNombre())));
        txt_apellido.setText((String.valueOf(titular.getApellido())));
        txt_nro_doc.setText((String.valueOf(titular.getDni())));
        txt_direccion.setText((String.valueOf(titular.getDomicilio())));
        Date date = titular.getFechaNac();
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = format.format(date);
        txt_fecha_nac.setValue(dateString);
        combobox_tipo_dni.setSelectedItem(titular.getTipoDni());;
        combobox_grupo_sanguineo.setSelectedItem(titular.getGrupoSanguineo());;
        combobox_factor_sanguineo.setSelectedItem(titular.getFactorSanguineo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_superior = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txt_titulo_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txt_titulo_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        txt_titulo_tipo_doc = new javax.swing.JLabel();
        combobox_tipo_dni = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        txt_titulo_num_doc = new javax.swing.JLabel();
        txt_nro_doc = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txt_titulo_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        txt_fecha_nacimiento = new javax.swing.JLabel();
        txt_fecha_nac = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 250), new java.awt.Dimension(400, 250), new java.awt.Dimension(400, 250));
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txt_titulo_grupo_sang = new javax.swing.JLabel();
        combobox_grupo_sanguineo = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        txt_titulo_factor_rh = new javax.swing.JLabel();
        combobox_factor_sanguineo = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(400, 250), new java.awt.Dimension(400, 250), new java.awt.Dimension(400, 250));
        jPanel_inferior = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        boton_atras = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        txt_mensaje_error = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        boton_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel_superior.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setPreferredSize(new java.awt.Dimension(1280, 120));
        jPanel_superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel4.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 120));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Usuario: ");
        jPanel6.add(jLabel8, new java.awt.GridBagConstraints());

        txt_user.setText("jLabel9");
        jPanel6.add(txt_user, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel15.setText("Nombre:");
        jPanel5.add(jLabel15, new java.awt.GridBagConstraints());

        txt_nombre_user.setText("jLabel9");
        jPanel5.add(txt_nombre_user, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel5);

        jPanel_superior.add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(750, 120));
        jPanel3.setMinimumSize(new java.awt.Dimension(750, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(750, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Titular");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel_superior.add(jPanel3);

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel_superior.add(jPanel1);

        getContentPane().add(jPanel_superior);

        jPanel2.setBorder(null);
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 500));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel9.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel9.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_titulo_nombre.setText("Nombre:");
        txt_titulo_nombre.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_nombre.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_nombre.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel10.add(txt_titulo_nombre);

        txt_nombre.setMaximumSize(new java.awt.Dimension(300, 35));
        txt_nombre.setMinimumSize(new java.awt.Dimension(300, 35));
        txt_nombre.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel10.add(txt_nombre);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_titulo_apellido.setText("Apellido:");
        txt_titulo_apellido.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_apellido.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_apellido.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel11.add(txt_titulo_apellido);

        txt_apellido.setMaximumSize(new java.awt.Dimension(300, 35));
        txt_apellido.setMinimumSize(new java.awt.Dimension(300, 35));
        txt_apellido.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel11.add(txt_apellido);

        jPanel9.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_titulo_tipo_doc.setText("Tipo Doc:");
        txt_titulo_tipo_doc.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_tipo_doc.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_tipo_doc.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel12.add(txt_titulo_tipo_doc);

        combobox_tipo_dni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "LC", "LE" }));
        combobox_tipo_dni.setMaximumSize(new java.awt.Dimension(300, 35));
        combobox_tipo_dni.setMinimumSize(new java.awt.Dimension(300, 35));
        combobox_tipo_dni.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel12.add(combobox_tipo_dni);

        jPanel9.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_titulo_num_doc.setText("N° Doc:");
        txt_titulo_num_doc.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_num_doc.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_num_doc.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel13.add(txt_titulo_num_doc);

        try {
            txt_nro_doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_nro_doc.setMaximumSize(new java.awt.Dimension(300, 35));
        txt_nro_doc.setMinimumSize(new java.awt.Dimension(300, 35));
        txt_nro_doc.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel13.add(txt_nro_doc);

        jPanel9.add(jPanel13);

        jPanel2.add(jPanel9);

        jPanel8.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel8.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_titulo_direccion.setText("Dirección:");
        txt_titulo_direccion.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_direccion.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_direccion.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel14.add(txt_titulo_direccion);

        txt_direccion.setMaximumSize(new java.awt.Dimension(300, 35));
        txt_direccion.setMinimumSize(new java.awt.Dimension(300, 35));
        txt_direccion.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel14.add(txt_direccion);

        jPanel8.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        txt_fecha_nacimiento.setText("Fecha Nac.:");
        txt_fecha_nacimiento.setMaximumSize(new java.awt.Dimension(85, 125));
        txt_fecha_nacimiento.setMinimumSize(new java.awt.Dimension(85, 125));
        txt_fecha_nacimiento.setPreferredSize(new java.awt.Dimension(85, 125));
        jPanel15.add(txt_fecha_nacimiento);

        try {
            txt_fecha_nac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fecha_nac.setMaximumSize(new java.awt.Dimension(200, 35));
        txt_fecha_nac.setMinimumSize(new java.awt.Dimension(200, 35));
        txt_fecha_nac.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel15.add(txt_fecha_nac);

        jLabel2.setText("(día-mes-año)");
        jPanel15.add(jLabel2);

        jPanel8.add(jPanel15);
        jPanel8.add(filler1);

        jPanel2.add(jPanel8);

        jPanel7.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_titulo_grupo_sang.setText("Grupo Sanguineo:");
        txt_titulo_grupo_sang.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_grupo_sang.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_grupo_sang.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel17.add(txt_titulo_grupo_sang);

        combobox_grupo_sanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "0", "AB" }));
        combobox_grupo_sanguineo.setMaximumSize(new java.awt.Dimension(300, 35));
        combobox_grupo_sanguineo.setMinimumSize(new java.awt.Dimension(300, 35));
        combobox_grupo_sanguineo.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel17.add(combobox_grupo_sanguineo);

        jPanel7.add(jPanel17);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        txt_titulo_factor_rh.setText("Factor RH:");
        txt_titulo_factor_rh.setMaximumSize(new java.awt.Dimension(75, 125));
        txt_titulo_factor_rh.setMinimumSize(new java.awt.Dimension(75, 125));
        txt_titulo_factor_rh.setPreferredSize(new java.awt.Dimension(75, 125));
        jPanel16.add(txt_titulo_factor_rh);

        combobox_factor_sanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        combobox_factor_sanguineo.setMaximumSize(new java.awt.Dimension(300, 35));
        combobox_factor_sanguineo.setMinimumSize(new java.awt.Dimension(300, 35));
        combobox_factor_sanguineo.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel16.add(combobox_factor_sanguineo);

        jPanel7.add(jPanel16);
        jPanel7.add(filler2);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2);

        jPanel_inferior.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel_inferior.setLayout(new javax.swing.BoxLayout(jPanel_inferior, javax.swing.BoxLayout.X_AXIS));

        jPanel19.setMaximumSize(new java.awt.Dimension(350, 100));
        jPanel19.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel19.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel19.setLayout(new java.awt.GridBagLayout());

        boton_atras.setText("Atras");
        boton_atras.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_atras.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_atras.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atrasActionPerformed(evt);
            }
        });
        boton_atras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_atrasKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 284, 36, 285);
        jPanel19.add(boton_atras, gridBagConstraints);

        jPanel_inferior.add(jPanel19);

        jPanel20.setMaximumSize(new java.awt.Dimension(580, 100));
        jPanel20.setMinimumSize(new java.awt.Dimension(580, 100));
        jPanel20.setPreferredSize(new java.awt.Dimension(580, 100));
        jPanel20.setRequestFocusEnabled(false);
        jPanel20.setLayout(new java.awt.GridBagLayout());

        txt_mensaje_error.setForeground(new java.awt.Color(255, 0, 0));
        txt_mensaje_error.setMaximumSize(new java.awt.Dimension(300, 100));
        txt_mensaje_error.setMinimumSize(new java.awt.Dimension(300, 100));
        txt_mensaje_error.setPreferredSize(new java.awt.Dimension(300, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 281);
        jPanel20.add(txt_mensaje_error, gridBagConstraints);

        jPanel_inferior.add(jPanel20);

        jPanel18.setMaximumSize(new java.awt.Dimension(350, 100));
        jPanel18.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel18.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        boton_modificar.setText("Modificar");
        boton_modificar.setMaximumSize(new java.awt.Dimension(200, 50));
        boton_modificar.setMinimumSize(new java.awt.Dimension(200, 50));
        boton_modificar.setPreferredSize(new java.awt.Dimension(200, 50));
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 0, 36, 0);
        jPanel18.add(boton_modificar, gridBagConstraints);

        jPanel_inferior.add(jPanel18);

        getContentPane().add(jPanel_inferior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atrasActionPerformed
        GestionLicencias obj = new GestionLicencias();
            obj.setVisible(true);
            dispose();
    }//GEN-LAST:event_boton_atrasActionPerformed

    private void boton_atrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_atrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           boton_atrasActionPerformed(null);
        }
    }//GEN-LAST:event_boton_atrasKeyPressed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        txt_nombre.setBackground(java.awt.Color.WHITE);
        txt_apellido.setBackground(java.awt.Color.WHITE);
        txt_direccion.setBackground(java.awt.Color.WHITE);
        txt_fecha_nac.setBackground(java.awt.Color.WHITE);
        txt_nro_doc.setBackground(java.awt.Color.WHITE);
        
        titular_aux.setNombre(txt_nombre.getText());
        titular_aux.setApellido(txt_apellido.getText());
        titular_aux.setDni(txt_nro_doc.getText());
        titular_aux.setTipoDni(combobox_tipo_dni.getSelectedItem().toString());
        titular_aux.setDomicilio(txt_direccion.getText());
        titular_aux.setFactorSanguineo(combobox_factor_sanguineo.getSelectedItem().toString());
        titular_aux.setGrupoSanguineo(combobox_grupo_sanguineo.getSelectedItem().toString());
        titular_aux.setAdministrativo(GestorAdministrativo.getInstance().getAdministrativo());
        java.util.Date fecha_ultima_actualizacion = new Date();
        titular_aux.setFechaUltimaActualizacion(fecha_ultima_actualizacion);
        
        String fecha_nacimiento_titular = txt_fecha_nac.getText();
        Date fechaNacimientoTitular = new Date();
        
        try {
            DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
            fechaNacimientoTitular = format.parse(fecha_nacimiento_titular);
            
            
        } catch (ParseException ex) {
            Logger.getLogger(NuevoTitular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        titular_aux.setFechaNac(fechaNacimientoTitular);
        
        
             if(txt_nombre.getText().equals("")||txt_apellido.getText().equals("")||txt_direccion.getText().equals("")||txt_nro_doc.getText().equals("        ")){
                txt_mensaje_error.setText("Algunos campos se encuentran en blanco");
                if (txt_nombre.getText().equals("")){
                    txt_nombre.requestFocus();
                    txt_nombre.setBackground(java.awt.Color.RED);
                }
                if (txt_apellido.getText().equals("")){
                    txt_apellido.requestFocus();
                    txt_apellido.setBackground(java.awt.Color.RED);
                }
                if (txt_direccion.getText().equals("")){
                    txt_direccion.requestFocus();
                    txt_direccion.setBackground(java.awt.Color.red);
                }
                if (txt_nro_doc.getText().equals("        ")){
                    txt_nro_doc.requestFocus();
                    txt_nro_doc.setBackground(java.awt.Color.red);
                }
             }
             else {
                 gestorTitular.modificarTitular(titular_aux);

                 JOptionPane.showMessageDialog(null, "El titular se ha modificado correctamente");
                 GestionLicencias obj = new GestionLicencias();
                 obj.setVisible(true);
                 dispose();
             }
                
        
    }//GEN-LAST:event_boton_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTitular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_atras;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JComboBox<String> combobox_factor_sanguineo;
    private javax.swing.JComboBox<String> combobox_grupo_sanguineo;
    private javax.swing.JComboBox<String> combobox_tipo_dni;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JFormattedTextField txt_fecha_nac;
    private javax.swing.JLabel txt_fecha_nacimiento;
    private javax.swing.JLabel txt_mensaje_error;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_nombre_user;
    private javax.swing.JFormattedTextField txt_nro_doc;
    private javax.swing.JLabel txt_titulo_apellido;
    private javax.swing.JLabel txt_titulo_direccion;
    private javax.swing.JLabel txt_titulo_factor_rh;
    private javax.swing.JLabel txt_titulo_grupo_sang;
    private javax.swing.JLabel txt_titulo_nombre;
    private javax.swing.JLabel txt_titulo_num_doc;
    private javax.swing.JLabel txt_titulo_tipo_doc;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
