/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Entidades.Titular;
import Gestores.GestorAdministrativo;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author augusto
 */
public class NuevoTitular extends javax.swing.JFrame {
    
    
    /**
     * Creates new form NuevoTitular
     */
    public NuevoTitular() {
        initComponents();
        setTitle("Nuevo Titular");
        setLocationRelativeTo(null);
        txt_username.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_usuario.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
    }
    
    public NuevoTitular(Titular nuevoTitular) {
        initComponents();
        setTitle("Nuevo Titular");
        setLocationRelativeTo(null);
        txt_username.setText(GestorAdministrativo.getInstance().getAdministrativo().getUsername());
        txt_nombre_usuario.setText(GestorAdministrativo.getInstance().getAdministrativo().getNombre() + " " + GestorAdministrativo.getInstance().getAdministrativo().getApellido());
        
        //se setean los datos no modificables (datos del titular)
        input_nombre_titular.setText(nuevoTitular.getNombre());
        input_apellido_titular.setText(nuevoTitular.getApellido());
        input_numero_doc.setText(nuevoTitular.getDni());
        input_direccion_titular.setText(nuevoTitular.getDomicilio());
        Date date = nuevoTitular.getFechaNac();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = format.format(date);
        input_fecha_nac_titular.setText(dateString);
        combo_tipo_doc.setSelectedItem(nuevoTitular.getTipoDni());
        combo_grupo_sanguineo.setSelectedItem(nuevoTitular.getGrupoSanguineo());
        combo_factor_rh.setSelectedItem(nuevoTitular.getFactorSanguineo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titulo_username = new javax.swing.JLabel();
        txt_titulo_nombre_usuario = new javax.swing.JLabel();
        txt_username = new javax.swing.JLabel();
        txt_nombre_usuario = new javax.swing.JLabel();
        txt_titulo_seccion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_titulo_nombre = new javax.swing.JLabel();
        txt_titulo_apellido = new javax.swing.JLabel();
        txt_titulo_tipo_doc = new javax.swing.JLabel();
        txt_titulo_num_doc = new javax.swing.JLabel();
        combo_tipo_doc = new javax.swing.JComboBox<>();
        input_nombre_titular = new javax.swing.JTextField();
        input_apellido_titular = new javax.swing.JTextField();
        txt_titulo_direccion = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JLabel();
        input_direccion_titular = new javax.swing.JTextField();
        input_fecha_nac_titular = new javax.swing.JFormattedTextField();
        txt_titulo_grupo_sang = new javax.swing.JLabel();
        txt_titulo_factor_rh = new javax.swing.JLabel();
        combo_grupo_sanguineo = new javax.swing.JComboBox<>();
        combo_factor_rh = new javax.swing.JComboBox<>();
        input_numero_doc = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        boton_emitir_licencia = new javax.swing.JButton();
        boton_pantalla_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_titulo_username.setText("Usuario:");

        txt_titulo_nombre_usuario.setText("Nombre:");

        txt_titulo_seccion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_titulo_seccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo_seccion.setText("Alta Titular");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_titulo_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_titulo_nombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txt_nombre_usuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_username)))
                .addGap(114, 114, 114)
                .addComponent(txt_titulo_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_username)
                    .addComponent(txt_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_nombre_usuario)
                    .addComponent(txt_nombre_usuario)))
            .addComponent(txt_titulo_seccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        txt_titulo_nombre.setText("Nombre:");

        txt_titulo_apellido.setText("Apellido:");

        txt_titulo_tipo_doc.setText("Tipo Doc:");

        txt_titulo_num_doc.setText("N° Doc:");

        combo_tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "LC", "LE" }));

        txt_titulo_direccion.setText("Dirección:");

        txt_fecha_nacimiento.setText("Fecha Nac.:");

        try {
            input_fecha_nac_titular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_fecha_nac_titular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_fecha_nac_titularActionPerformed(evt);
            }
        });

        txt_titulo_grupo_sang.setText("Grupo Sanguineo:");

        txt_titulo_factor_rh.setText("Factor RH:");

        combo_grupo_sanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "0", "AB" }));

        combo_factor_rh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        try {
            input_numero_doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titulo_nombre)
                            .addComponent(txt_titulo_apellido))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_apellido_titular)
                            .addComponent(input_nombre_titular))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titulo_direccion)
                            .addComponent(txt_fecha_nacimiento))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_direccion_titular)
                            .addComponent(input_fecha_nac_titular, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_titulo_factor_rh)
                            .addComponent(txt_titulo_grupo_sang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_factor_rh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_grupo_sanguineo, 0, 75, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titulo_tipo_doc)
                            .addComponent(txt_titulo_num_doc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_tipo_doc, 0, 138, Short.MAX_VALUE)
                            .addComponent(input_numero_doc))
                        .addGap(593, 593, 593))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_nombre_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo_direccion)
                    .addComponent(input_direccion_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo_grupo_sang)
                    .addComponent(combo_grupo_sanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_apellido)
                    .addComponent(input_apellido_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha_nacimiento)
                    .addComponent(input_fecha_nac_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo_factor_rh)
                    .addComponent(combo_factor_rh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_tipo_doc)
                    .addComponent(combo_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_num_doc)
                    .addComponent(input_numero_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        boton_emitir_licencia.setText("Emitir Licencia");
        boton_emitir_licencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_emitir_licenciaActionPerformed(evt);
            }
        });

        boton_pantalla_atras.setText("Atras");
        boton_pantalla_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pantalla_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_pantalla_atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_emitir_licencia)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_emitir_licencia)
                    .addComponent(boton_pantalla_atras))
                .addContainerGap())
        );

        boton_pantalla_atras.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_pantalla_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pantalla_atrasActionPerformed
        GestionLicencias obj = new GestionLicencias();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_pantalla_atrasActionPerformed

    private void boton_emitir_licenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_emitir_licenciaActionPerformed
        String nombre_titular = input_nombre_titular.getText();
        String apellido_titular = input_apellido_titular.getText();
        String tipo_doc = combo_tipo_doc.getSelectedItem().toString();
        String numero_doc = input_numero_doc.getText();
        String direccion_titular = input_direccion_titular.getText();
        String fecha_nacimiento_titular = input_fecha_nac_titular.getText();
        String grupo_sanguineo = combo_grupo_sanguineo.getSelectedItem().toString();
        String factor_rh = combo_factor_rh.getSelectedItem().toString();
        
        Date fechaNacimientoTitular = new Date();
        
        try {
            
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            fechaNacimientoTitular = format.parse(fecha_nacimiento_titular);
            
        } catch (ParseException ex) {
            Logger.getLogger(NuevoTitular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(fechaNacimientoTitular);
        
        Titular nuevoTitular = new Titular();
        
        nuevoTitular.setNombre(nombre_titular);
        nuevoTitular.setApellido(apellido_titular);
        nuevoTitular.setTipoDni(tipo_doc);
        nuevoTitular.setDni(numero_doc);
        nuevoTitular.setDomicilio(direccion_titular);
        nuevoTitular.setFechaNac(fechaNacimientoTitular);
        nuevoTitular.setGrupoSanguineo(grupo_sanguineo);
        nuevoTitular.setFactorSanguineo(factor_rh);
        
        EmitirLicencia pantalla = new EmitirLicencia(nuevoTitular);
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_emitir_licenciaActionPerformed

    private void input_fecha_nac_titularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_fecha_nac_titularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_fecha_nac_titularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTitular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTitular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_emitir_licencia;
    private javax.swing.JButton boton_pantalla_atras;
    private javax.swing.JComboBox<String> combo_factor_rh;
    private javax.swing.JComboBox<String> combo_grupo_sanguineo;
    private javax.swing.JComboBox<String> combo_tipo_doc;
    private javax.swing.JTextField input_apellido_titular;
    private javax.swing.JTextField input_direccion_titular;
    private javax.swing.JFormattedTextField input_fecha_nac_titular;
    private javax.swing.JTextField input_nombre_titular;
    private javax.swing.JFormattedTextField input_numero_doc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txt_fecha_nacimiento;
    private javax.swing.JLabel txt_nombre_usuario;
    private javax.swing.JLabel txt_titulo_apellido;
    private javax.swing.JLabel txt_titulo_direccion;
    private javax.swing.JLabel txt_titulo_factor_rh;
    private javax.swing.JLabel txt_titulo_grupo_sang;
    private javax.swing.JLabel txt_titulo_nombre;
    private javax.swing.JLabel txt_titulo_nombre_usuario;
    private javax.swing.JLabel txt_titulo_num_doc;
    private javax.swing.JLabel txt_titulo_seccion;
    private javax.swing.JLabel txt_titulo_tipo_doc;
    private javax.swing.JLabel txt_titulo_username;
    private javax.swing.JLabel txt_username;
    // End of variables declaration//GEN-END:variables
}
