package Entidades;
// Generated Oct 23, 2018 11:34:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administrativo generated by hbm2java
 */
public class Administrativo  implements java.io.Serializable {


     private Integer idAdministrativo;
     private String nombre;
     private String apellido;
     private String dni;
     private String username;
     private String password;
     private int superuser;
     private int user_nuevo;
     private Set licencias = new HashSet(0);

    public Administrativo() {
    }

	
    public Administrativo(String nombre, String apellido, String dni, String username, String password, int superuser, int user_nuevo) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.username = username;
        this.password = password;
        this.superuser = superuser;
        this.user_nuevo = user_nuevo;
    }
    public Administrativo(String nombre, String apellido, String dni, String username, String password, int superuser, int user_nuevo, Set licencias) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.username = username;
       this.password = password;
       this.superuser = superuser;
       this.user_nuevo = user_nuevo;
       this.licencias = licencias;
    }
   
    public Integer getIdAdministrativo() {
        return this.idAdministrativo;
    }
    
    public void setIdAdministrativo(Integer idAdministrativo) {
        this.idAdministrativo = idAdministrativo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public int getSuperuser() {
        return superuser;
    }

    public void setSuperuser(int superuser) {
        this.superuser = superuser;
    }

    public int getUser_nuevo() {
        return user_nuevo;
    }

    public void setUser_nuevo(int user_nuevo) {
        this.user_nuevo = user_nuevo;
    }
    
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


