package Entidades;
// Generated Oct 11, 2018 11:50:31 AM by Hibernate Tools 4.3.1



/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private int idTitular;
     private String nombre;
     private String apellido;
     private int dni;
     private String domicilio;

    public Titular() {
    }

    public Titular(int idTitular, String nombre, String apellido, int dni, String domicilio) {
       this.idTitular = idTitular;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.domicilio = domicilio;
    }
   
    public int getIdTitular() {
        return this.idTitular;
    }
    
    public void setIdTitular(int idTitular) {
        this.idTitular = idTitular;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }




}


