package Entidades;
// Generated Oct 23, 2018 11:34:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private int idTitular;
     private String nombre;
     private String apellido;
     private String dni;
     private String domicilio;
     private Date fechaNac;
     private String tipoDni;
     private String grupoSanguineo;
     private String factorSanguineo;
     private Administrativo administrativo;
     private Date fechaUltimaActualizacion;
     private Set licencias = new HashSet(0);

    public Titular() {
    }

	
    public Titular(int idTitular, String nombre, String apellido, String dni, String domicilio, Date fechaNac, String tipoDni, String grupoSanguineo, String factorSanguineo, Administrativo administrativo, Date fechaUltimaActualizacion) {
        this.idTitular = idTitular;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.domicilio = domicilio;
        this.fechaNac = fechaNac;
        this.tipoDni = tipoDni;
        this.grupoSanguineo = grupoSanguineo;
        this.factorSanguineo = factorSanguineo;
        this.administrativo = administrativo;
        this.fechaUltimaActualizacion = fechaUltimaActualizacion;
    }
    public Titular(int idTitular, String nombre, String apellido, String dni, String domicilio, Date fechaNac, String tipoDni, String grupoSanguineo, String factorSanguineo, Administrativo administrativo, Date fechaUltimaActualizacion, Set licencias) {
       this.idTitular = idTitular;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.domicilio = domicilio;
       this.fechaNac = fechaNac;
       this.tipoDni = tipoDni;
       this.grupoSanguineo = grupoSanguineo;
       this.factorSanguineo = factorSanguineo;
       this.administrativo = administrativo;
       this.fechaUltimaActualizacion = fechaUltimaActualizacion;
       this.licencias = licencias;
    }

    public void setAdministrativo(Administrativo administrativo) {
        this.administrativo = administrativo;
    }

    public void setFechaUltimaActualizacion(Date fechaUltimaActualizacion) {
        this.fechaUltimaActualizacion = fechaUltimaActualizacion;
    }

    public Administrativo getAdministrativo() {
        return administrativo;
    }

    public Date getFechaUltimaActualizacion() {
        return fechaUltimaActualizacion;
    }
   
    public int getIdTitular() {
        return this.idTitular;
    }
    
    public void setIdTitular(int idTitular) {
        this.idTitular = idTitular;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTipoDni() {
        return this.tipoDni;
    }
    
    public void setTipoDni(String tipoDni) {
        this.tipoDni = tipoDni;
    }
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
    public String getFactorSanguineo() {
        return this.factorSanguineo;
    }
    
    public void setFactorSanguineo(String factorSanguineo) {
        this.factorSanguineo = factorSanguineo;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


