package Entidades;
// Generated Oct 23, 2018 11:34:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titular generated by hbm2java
 */
public class TitularAuxParaTabla  implements java.io.Serializable {


     private int idTitular;
     private String nombre;
     private String apellido;
     private String dni;
     private String domicilio;
     private Date fechaNac;
     private String tipoDni;
     private String grupoSanguineo;
     private String factorSanguineo;
     private Set licencias = new HashSet(0);
     
//agregamos estos datos para mostrarlos en la tabla para cada licencia que tenga
     private Date fechaVenc;
     private String clase;
     private String estado;

    public Date getFechaVenc() {
        return fechaVenc;
    }

    public String getClase() {
        return clase;
    }

    public String getEstado() {
        return estado;
    }

    public void setFechaVenc(Date fechaVenc) {
        this.fechaVenc = fechaVenc;
    }

    public void setClase(String clase) {
        this.clase = clase;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
     

    public TitularAuxParaTabla() {
    }

	
    public TitularAuxParaTabla(int idTitular, String nombre, String apellido, String dni, String domicilio, Date fechaNac, String tipoDni, String grupoSanguineo, String factorSanguineo) {
        this.idTitular = idTitular;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.domicilio = domicilio;
        this.fechaNac = fechaNac;
        this.tipoDni = tipoDni;
        this.grupoSanguineo = grupoSanguineo;
        this.factorSanguineo = factorSanguineo;
    }
    public TitularAuxParaTabla(int idTitular, String nombre, String apellido, String dni, String domicilio, Date fechaNac, String tipoDni, String grupoSanguineo, String factorSanguineo, Set licencias) {
       this.idTitular = idTitular;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.domicilio = domicilio;
       this.fechaNac = fechaNac;
       this.tipoDni = tipoDni;
       this.grupoSanguineo = grupoSanguineo;
       this.factorSanguineo = factorSanguineo;
       this.licencias = licencias;
    }
   
    public int getIdTitular() {
        return this.idTitular;
    }
    
    public void setIdTitular(int idTitular) {
        this.idTitular = idTitular;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTipoDni() {
        return this.tipoDni;
    }
    
    public void setTipoDni(String tipoDni) {
        this.tipoDni = tipoDni;
    }
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
    public String getFactorSanguineo() {
        return this.factorSanguineo;
    }
    
    public void setFactorSanguineo(String factorSanguineo) {
        this.factorSanguineo = factorSanguineo;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


